package database

import (
	"fmt"
	"log/slog"
	"strings"
	"time"

	"gorm.io/gorm"
)

// installLogPartitioning переводит request_logs на нативное партиционирование
// Postgres по created_at (суточные партиции). Идемпотентна: на уже
// партиционированной таблице только досоздаёт ближайшие партиции. Существующую
// непартиционированную таблицу (legacy от AutoMigrate) переименовывает в
// request_logs_legacy - данные сохраняются для ручного разбора, а не теряются.
//
// Вызывается ДО db.AutoMigrate, поэтому request_logs исключена из AllModels:
// нативное партиционирование несовместимо с GORM AutoMigrate.
func installLogPartitioning(db *gorm.DB) error {
	// Сериализуем установку транзакционным advisory-lock: при параллельных
	// AutoMigrate (тесты -p на одной БД) была гонка между проверкой «партиционирована?»
	// и CREATE TABLE, дававшая duplicate key. Lock выстраивает вызовы в очередь и
	// освобождается на commit, так что второй уже видит готовую таблицу.
	return db.Transaction(func(tx *gorm.DB) error {
		if err := tx.Exec("SELECT pg_advisory_xact_lock(728931)").Error; err != nil {
			return err
		}
		if err := ensurePartitionedRequestLogs(tx); err != nil {
			return fmt.Errorf("partition request_logs: %w", err)
		}
		if err := ensureRequestLogsDaily(tx); err != nil {
			return fmt.Errorf("request_logs_daily: %w", err)
		}
		if err := ensureLogDurationColumns(tx); err != nil {
			return err
		}
		if err := ensureLogFilterIndexes(tx); err != nil {
			return err
		}
		// Партиции на вчера..+7 дней, чтобы запись не падала до первого прохода воркера.
		now := time.Now().UTC()
		if err := ensureDailyPartitions(tx, "request_logs", now.AddDate(0, 0, -1), now.AddDate(0, 0, 7)); err != nil {
			return fmt.Errorf("precreate request_logs partitions: %w", err)
		}

		// pd_audit_logs (аудит ПД, 152-ФЗ): помесячные партиции, retention годами,
		// без агрегации - аудит хранится построчно и дропается по сроку.
		if err := ensurePartitionedPDAudit(tx); err != nil {
			return fmt.Errorf("partition pd_audit_logs: %w", err)
		}
		if err := ensureMonthlyPartitions(tx, "pd_audit_logs", now.AddDate(0, -1, 0), now.AddDate(0, 2, 0)); err != nil {
			return fmt.Errorf("precreate pd_audit partitions: %w", err)
		}
		return nil
	})
}

// ensurePartitionedRequestLogs создаёт партиционированную request_logs, если её
// ещё нет или она непартиционированная.
func ensurePartitionedRequestLogs(db *gorm.DB) error {
	var partitioned bool
	if err := db.Raw(`
		SELECT EXISTS (
			SELECT 1 FROM pg_partitioned_table pt
			JOIN pg_class c ON c.oid = pt.partrelid
			WHERE c.relname = 'request_logs'
		)`).Scan(&partitioned).Error; err != nil {
		return err
	}
	if partitioned {
		return nil
	}

	var exists bool
	if err := db.Raw(`
		SELECT EXISTS (
			SELECT 1 FROM pg_class WHERE relname = 'request_logs' AND relkind = 'r'
		)`).Scan(&exists).Error; err != nil {
		return err
	}
	if exists {
		// Старую непартиционированную таблицу сохраняем под другим именем -
		// технические логи можно разобрать/дропнуть вручную.
		if err := db.Exec(`ALTER TABLE request_logs RENAME TO request_logs_legacy`).Error; err != nil {
			return err
		}
		slog.Warn("request_logs переименована в request_logs_legacy для перехода на партиционирование")
	}

	if err := db.Exec(`
		CREATE TABLE request_logs (
			id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
			user_id         INTEGER,
			username        VARCHAR(100),
			method          VARCHAR(10),
			url             VARCHAR(500),
			headers         JSONB,
			request_body    TEXT,
			response_status INTEGER,
			response_body   TEXT,
			duration_ms     INTEGER,
			duration_us     BIGINT,
			created_at      TIMESTAMPTZ NOT NULL,
			PRIMARY KEY (id, created_at)
		) PARTITION BY RANGE (created_at)`).Error; err != nil {
		return err
	}
	slog.Info("request_logs создана как партиционированная по created_at")
	return nil
}

// ensureLogFilterIndexes держит индексы request_logs под фильтры экрана мониторинга.
// Вызывается отдельно от создания таблицы: на уже установленных стендах таблица давно
// есть, а индексов под статус и метод не было - выборка «только ошибки» шла
// последовательным чтением всех партиций.
//
// Статус и метод идут в паре с created_at: журнал всегда читается за период и всегда
// в порядке от свежих записей, поэтому одиночный индекс по статусу пришлось бы
// досортировывать. CREATE INDEX на партиционированной таблице сам расходится по
// партициям, включая созданные позже.
func ensureLogFilterIndexes(db *gorm.DB) error {
	stmts := []string{
		`CREATE INDEX IF NOT EXISTS idx_request_logs_created_at ON request_logs (created_at)`,
		`CREATE INDEX IF NOT EXISTS idx_request_logs_user_id ON request_logs (user_id)`,
		`CREATE INDEX IF NOT EXISTS idx_request_logs_status_created ON request_logs (response_status, created_at DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_request_logs_method_created ON request_logs (method, created_at DESC)`,
	}
	for _, stmt := range stmts {
		if err := db.Exec(stmt).Error; err != nil {
			return fmt.Errorf("index request_logs: %w", err)
		}
	}
	return nil
}

// ensureRequestLogsDaily создаёт таблицу дневных агрегатов логов - компактную
// сводку для экрана истории. Детальные партиции старше retention сворачиваются
// сюда воркером. user_id=0 означает анонимный запрос (NULL в PK недопустим).
func ensureRequestLogsDaily(db *gorm.DB) error {
	return db.Exec(`
		CREATE TABLE IF NOT EXISTS request_logs_daily (
			day             DATE        NOT NULL,
			user_id         INTEGER     NOT NULL DEFAULT 0,
			endpoint        TEXT        NOT NULL,
			method          VARCHAR(10) NOT NULL,
			status_class    SMALLINT    NOT NULL,
			request_count   BIGINT      NOT NULL,
			error_count     BIGINT      NOT NULL,
			avg_duration_ms INTEGER     NOT NULL,
			p95_duration_ms INTEGER     NOT NULL,
			avg_duration_us BIGINT      NOT NULL DEFAULT 0,
			p95_duration_us BIGINT      NOT NULL DEFAULT 0,
			PRIMARY KEY (day, user_id, endpoint, method, status_class)
		)`).Error
}

// ensureLogDurationColumns досоздаёт микросекундные колонки длительности на уже
// установленных стендах. Миллисекунды остаются как есть: они округлены вниз, и
// треть запросов отвечает быстрее миллисекунды, из-за чего перцентили по ним
// вырождались в ноль (#2125). ADD COLUMN на партиционированной таблице
// распространяется на все партиции сам.
func ensureLogDurationColumns(db *gorm.DB) error {
	stmts := []string{
		`ALTER TABLE request_logs ADD COLUMN IF NOT EXISTS duration_us BIGINT`,
		`ALTER TABLE request_logs_daily ADD COLUMN IF NOT EXISTS avg_duration_us BIGINT NOT NULL DEFAULT 0`,
		`ALTER TABLE request_logs_daily ADD COLUMN IF NOT EXISTS p95_duration_us BIGINT NOT NULL DEFAULT 0`,
	}
	for _, stmt := range stmts {
		if err := db.Exec(stmt).Error; err != nil {
			return fmt.Errorf("add duration column: %w", err)
		}
	}
	return nil
}

// partitionSuffix возвращает суффикс суточной партиции вида 2026_06_21.
func partitionSuffix(t time.Time) string {
	return t.UTC().Format("2006_01_02")
}

// ensureDailyPartitions создаёт суточные партиции parent в диапазоне дат
// [from, to] включительно (по дню). CREATE TABLE IF NOT EXISTS идемпотентен.
// Даты формируются из time.Time, не из пользовательского ввода - инъекции нет.
func ensureDailyPartitions(db *gorm.DB, parent string, from, to time.Time) error {
	d := time.Date(from.Year(), from.Month(), from.Day(), 0, 0, 0, 0, time.UTC)
	end := time.Date(to.Year(), to.Month(), to.Day(), 0, 0, 0, 0, time.UTC)
	for !d.After(end) {
		next := d.AddDate(0, 0, 1)
		part := fmt.Sprintf("%s_%s", parent, partitionSuffix(d))
		stmt := fmt.Sprintf(
			`CREATE TABLE IF NOT EXISTS %s PARTITION OF %s FOR VALUES FROM ('%s') TO ('%s')`,
			part, parent, d.Format("2006-01-02"), next.Format("2006-01-02"),
		)
		if err := db.Exec(stmt).Error; err != nil {
			return fmt.Errorf("create partition %s: %w", part, err)
		}
		d = next
	}
	return nil
}

// MaintainLogPartitions выполняет суточное обслуживание партиций request_logs:
// досоздаёт партиции на precreateDays вперёд, сворачивает партиции старше
// detailDays в дневные агрегаты request_logs_daily и дропает их. Разово
// сворачивает request_logs_legacy (бэкап старой непартиционированной таблицы),
// если она осталась после миграции.
func MaintainLogPartitions(db *gorm.DB, detailDays, precreateDays, pdRetentionMonths int) error {
	now := time.Now().UTC()
	if err := ensureDailyPartitions(db, "request_logs", now, now.AddDate(0, 0, precreateDays)); err != nil {
		return fmt.Errorf("precreate partitions: %w", err)
	}

	// pd_audit_logs: партиции на 2 месяца вперёд + дроп старше retention (152-ФЗ).
	if err := ensureMonthlyPartitions(db, "pd_audit_logs", now, now.AddDate(0, 2, 0)); err != nil {
		slog.Error("precreate pd_audit partitions", "error", err)
	}
	dropOldMonthlyPartitions(db, "pd_audit_logs", now.AddDate(0, -pdRetentionMonths, 0))

	// Разовое сворачивание legacy-бэкапа: агрегируем старые логи и дропаем таблицу.
	rollupLegacyRequestLogs(db)

	cutoff := time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, time.UTC).AddDate(0, 0, -detailDays)
	parts, err := listLogPartitions(db, "request_logs")
	if err != nil {
		return err
	}
	for _, p := range parts {
		if !p.day.Before(cutoff) {
			continue
		}
		if err := aggregateLogTable(db, p.name); err != nil {
			slog.Error("aggregate log partition", "partition", p.name, "error", err)
			continue // непросуммированную партицию не дропаем
		}
		if err := db.Exec("DROP TABLE IF EXISTS " + p.name).Error; err != nil {
			slog.Error("drop log partition", "partition", p.name, "error", err)
			continue
		}
		slog.Info("свёрнута и удалена партиция логов", "partition", p.name)
	}
	return nil
}

type logPartition struct {
	name string
	day  time.Time
}

// listLogPartitions возвращает партиции parent с распарсенной из имени датой.
func listLogPartitions(db *gorm.DB, parent string) ([]logPartition, error) {
	var names []string
	if err := db.Raw(`
		SELECT c.relname FROM pg_class c
		JOIN pg_inherits i ON i.inhrelid = c.oid
		JOIN pg_class p ON p.oid = i.inhparent
		WHERE p.relname = ?`, parent).Scan(&names).Error; err != nil {
		return nil, err
	}
	out := make([]logPartition, 0, len(names))
	prefix := parent + "_"
	for _, n := range names {
		day, err := time.Parse("2006_01_02", strings.TrimPrefix(n, prefix))
		if err != nil {
			continue // не суточная партиция нашей схемы
		}
		out = append(out, logPartition{name: n, day: day})
	}
	return out, nil
}

// rollupLegacyRequestLogs сворачивает request_logs_legacy в дневные агрегаты и
// дропает её. No-op, если таблицы нет (чистые стенды).
func rollupLegacyRequestLogs(db *gorm.DB) {
	var exists bool
	if err := db.Raw(`SELECT EXISTS(SELECT 1 FROM pg_class WHERE relname='request_logs_legacy' AND relkind='r')`).
		Scan(&exists).Error; err != nil || !exists {
		return
	}
	if err := aggregateLogTable(db, "request_logs_legacy"); err != nil {
		slog.Error("aggregate request_logs_legacy", "error", err)
		return
	}
	if err := db.Exec(`DROP TABLE IF EXISTS request_logs_legacy`).Error; err != nil {
		slog.Error("drop request_logs_legacy", "error", err)
		return
	}
	slog.Info("request_logs_legacy свёрнута в агрегаты и удалена")
}

// LogEndpointExpr -- нормализованный маршрут запроса: query-строка отброшена,
// числовые сегменты пути заменены на :id, чтобы записи схлопывались по
// логическому маршруту.
//
// Выражение общее со свёрткой намеренно: «Аналитика» дочитывает дни новее
// последней свёртки прямо из детальных партиций и складывает их с агрегатами.
// Разъедься нормализация -- один и тот же маршрут пришёл бы в топ двумя строками.
//
// Разделитель адреса и query задан как chr(63): знак вопроса в кавычках gorm
// принимает за место подстановки и разъезжается на аргументах запроса (#2125).
const LogEndpointExpr = `regexp_replace(split_part(COALESCE(url, ''), chr(63), 1), '/[0-9]+', '/:id', 'g')`

// aggregateLogTable сворачивает таблицу/партицию логов в request_logs_daily.
func aggregateLogTable(db *gorm.DB, table string) error {
	stmt := fmt.Sprintf(`
		INSERT INTO request_logs_daily
			(day, user_id, endpoint, method, status_class,
			 request_count, error_count, avg_duration_ms, p95_duration_ms,
			 avg_duration_us, p95_duration_us)
		SELECT
			created_at::date,
			COALESCE(user_id, 0),
			`+LogEndpointExpr+`,
			COALESCE(method, ''),
			COALESCE(response_status, 0) / 100,
			count(*),
			count(*) FILTER (WHERE response_status >= 400),
			COALESCE(avg(duration_ms), 0)::int,
			COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY duration_ms), 0)::int,
			COALESCE(avg(COALESCE(duration_us, duration_ms * 1000)), 0)::bigint,
			COALESCE(percentile_cont(0.95) WITHIN GROUP (
				ORDER BY COALESCE(duration_us, duration_ms * 1000)), 0)::bigint
		FROM %s
		GROUP BY 1, 2, 3, 4, 5
		ON CONFLICT (day, user_id, endpoint, method, status_class) DO UPDATE SET
			request_count   = request_logs_daily.request_count + EXCLUDED.request_count,
			error_count     = request_logs_daily.error_count + EXCLUDED.error_count,
			avg_duration_ms = EXCLUDED.avg_duration_ms,
			p95_duration_ms = EXCLUDED.p95_duration_ms,
			avg_duration_us = EXCLUDED.avg_duration_us,
			p95_duration_us = EXCLUDED.p95_duration_us`, table)
	return db.Exec(stmt).Error
}

// ensurePartitionedPDAudit создаёт партиционированную помесячно pd_audit_logs.
// Существующую непартиционированную сохраняет как pd_audit_logs_legacy - аудит ПД
// терять нельзя (152-ФЗ), сворачивать в агрегаты тоже нельзя (нужен построчно).
func ensurePartitionedPDAudit(db *gorm.DB) error {
	var partitioned bool
	if err := db.Raw(`SELECT EXISTS(SELECT 1 FROM pg_partitioned_table pt JOIN pg_class c ON c.oid=pt.partrelid WHERE c.relname='pd_audit_logs')`).Scan(&partitioned).Error; err != nil {
		return err
	}
	if partitioned {
		return nil
	}
	var exists bool
	if err := db.Raw(`SELECT EXISTS(SELECT 1 FROM pg_class WHERE relname='pd_audit_logs' AND relkind='r')`).Scan(&exists).Error; err != nil {
		return err
	}
	if exists {
		if err := db.Exec(`ALTER TABLE pd_audit_logs RENAME TO pd_audit_logs_legacy`).Error; err != nil {
			return err
		}
		slog.Warn("pd_audit_logs переименована в pd_audit_logs_legacy (аудит ПД сохранён)")
	}
	if err := db.Exec(`
		CREATE TABLE pd_audit_logs (
			id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
			user_id     INTEGER,
			username    VARCHAR(100),
			action      VARCHAR(50),
			resource    VARCHAR(100),
			resource_id INTEGER,
			ip_address  VARCHAR(45),
			method      VARCHAR(10),
			path        VARCHAR(500),
			status_code INTEGER,
			created_at  TIMESTAMPTZ NOT NULL,
			PRIMARY KEY (id, created_at)
		) PARTITION BY RANGE (created_at)`).Error; err != nil {
		return err
	}
	for _, idx := range []string{
		`CREATE INDEX IF NOT EXISTS idx_pd_audit_created_at ON pd_audit_logs (created_at)`,
		`CREATE INDEX IF NOT EXISTS idx_pd_audit_user_id ON pd_audit_logs (user_id)`,
		`CREATE INDEX IF NOT EXISTS idx_pd_audit_action ON pd_audit_logs (action)`,
		`CREATE INDEX IF NOT EXISTS idx_pd_audit_resource ON pd_audit_logs (resource)`,
	} {
		if err := db.Exec(idx).Error; err != nil {
			return err
		}
	}
	slog.Info("pd_audit_logs создана как партиционированная по created_at")
	return nil
}

// ensureMonthlyPartitions создаёт месячные партиции parent в диапазоне [from, to]
// (по месяцу). Идемпотентно.
func ensureMonthlyPartitions(db *gorm.DB, parent string, from, to time.Time) error {
	m := time.Date(from.Year(), from.Month(), 1, 0, 0, 0, 0, time.UTC)
	end := time.Date(to.Year(), to.Month(), 1, 0, 0, 0, 0, time.UTC)
	for !m.After(end) {
		next := m.AddDate(0, 1, 0)
		part := fmt.Sprintf("%s_%s", parent, m.Format("2006_01"))
		stmt := fmt.Sprintf(
			`CREATE TABLE IF NOT EXISTS %s PARTITION OF %s FOR VALUES FROM ('%s') TO ('%s')`,
			part, parent, m.Format("2006-01-02"), next.Format("2006-01-02"),
		)
		if err := db.Exec(stmt).Error; err != nil {
			return fmt.Errorf("create monthly partition %s: %w", part, err)
		}
		m = next
	}
	return nil
}

// dropOldMonthlyPartitions дропает месячные партиции parent старше cutoff-месяца
// без агрегации (для pd_audit_logs - аудит просто удаляется по сроку retention).
func dropOldMonthlyPartitions(db *gorm.DB, parent string, cutoff time.Time) {
	var names []string
	if err := db.Raw(`
		SELECT c.relname FROM pg_class c
		JOIN pg_inherits i ON i.inhrelid = c.oid
		JOIN pg_class p ON p.oid = i.inhparent
		WHERE p.relname = ?`, parent).Scan(&names).Error; err != nil {
		slog.Error("list monthly partitions", "parent", parent, "error", err)
		return
	}
	prefix := parent + "_"
	cm := time.Date(cutoff.Year(), cutoff.Month(), 1, 0, 0, 0, 0, time.UTC)
	for _, n := range names {
		m, err := time.Parse("2006_01", strings.TrimPrefix(n, prefix))
		if err != nil {
			continue
		}
		if m.Before(cm) {
			if err := db.Exec("DROP TABLE IF EXISTS " + n).Error; err != nil {
				slog.Error("drop monthly partition", "partition", n, "error", err)
				continue
			}
			slog.Info("удалена партиция аудита по сроку retention", "partition", n)
		}
	}
}
