module.exports = {
  ...require('./LoginPage'),
  ...require('./NavigationBar'),
  ...require('./HeaderBar'),
  ...require('./CabinetPage'),
  ...require('./ApplicationCenterPage'),
  ...require('./CarsPage'),
  ...require('./EmployeesPage'),
  ...require('./CreateApplicationPage'),
  ...require('./TablesPage'),
  ...require('./ApplicationDetailModal'),
  ...require('./SupplementModal'),
  ...require('./EmployeeFormSection'),
  ...require('./PeopleTablePage'),
  ...require('./NotificationsDropdown'),
  ...require('./NotificationDetailModal'),
};
