name: Bug Report
description: Сообщить о баге
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Описание бага
      placeholder: Что произошло?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Шаги для воспроизведения
      placeholder: |
        1. Зайти на страницу...
        2. Нажать...
        3. Увидеть ошибку
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Ожидаемое поведение
      placeholder: Что должно было произойти?
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Приоритет
      options:
        - Высокий
        - Средний
        - Низкий
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Область
      options:
        - Frontend
        - Backend
        - CI/CD
        - Другое
    validations:
      required: false
