<template>
  <svg
    width="16"
    height="16"
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    aria-hidden="true"
  >
    <rect
      x="2"
      y="3"
      width="16"
      height="14"
      rx="3"
      stroke="currentColor"
      stroke-width="1.6"
    />
    <line
      x1="6"
      y1="8"
      x2="14"
      y2="8"
      stroke="currentColor"
      stroke-width="1.6"
      stroke-linecap="round"
    />
    <line
      x1="6"
      y1="11"
      x2="14"
      y2="11"
      stroke="currentColor"
      stroke-width="1.6"
      stroke-linecap="round"
    />
    <line
      x1="6"
      y1="14"
      x2="11"
      y2="14"
      stroke="currentColor"
      stroke-width="1.6"
      stroke-linecap="round"
    />
  </svg>
</template>

<script>
export default {
  name: 'DetailsIcon'
}
</script>
