package handlers_test

import (
	"testing"
	"time"

	"systemburo/internal/models"
	"systemburo/internal/services"

	"github.com/stretchr/testify/require"
	"gorm.io/gorm"
)

func bindPassageFixtureCar2667(t *testing.T, db *gorm.DB, carID, tableID int) {
	t.Helper()
	require.NoError(t, db.Create(&models.CarTargetTable{
		CarID: carID, TableID: tableID, Source: "application",
	}).Error)
}

// Direct insertion deliberately avoids a create audit: callers verify exactly
// the passage history generated by their own request, not manual-create history.
func preparePassageFixtureEmployee2667(t *testing.T, db *gorm.DB, employeeID, tableID, organizationID int, inside bool) {
	t.Helper()
	clock := time.Now().UTC().In(services.MoscowLocation())
	from, to := clock.AddDate(0, 0, -1).Format("2006-01-02"), clock.AddDate(0, 0, 1).Format("2006-01-02")
	start, end, active := "00:00", "23:59", 1
	attachment := models.Attachment{
		AttachmentType: "people", IsManual: true, OrganizationID: &organizationID, Status: &active,
		EntryDateFrom: &from, EntryDateTo: &to, EntryTimeFrom: &start, EntryTimeTo: &end,
	}
	require.NoError(t, db.Create(&attachment).Error)
	updates := map[string]any{"attachment_id": attachment.ID, "status": active}
	if inside {
		// Existing inside cache without an entry event is the approved legacy case.
		updates["territory_status"] = 1
	}
	require.NoError(t, db.Model(&models.Employee{}).Where("id = ?", employeeID).Updates(updates).Error)
	var count int64
	require.NoError(t, db.Model(&models.EmployeeTargetTable{}).
		Where("employee_id = ? AND table_id = ?", employeeID, tableID).Count(&count).Error)
	if count == 0 {
		require.NoError(t, db.Create(&models.EmployeeTargetTable{
			EmployeeID: employeeID, TableID: tableID, Source: "manual",
		}).Error)
	}
}
