package handlers_test

// routeAccessRegistry - решение о доступе к каждому методу API, ключ "METHOD путь"
// в нотации echo. Сверяет с роутером и с ответами сервера TestRouteAccess_Registry
// (route_access_test.go): новый метод без записи, запись без метода и расхождение
// записи с поведением роняют тест. Причина пишется для человека, который через год
// спросит, почему метод доступен именно так.
var routeAccessRegistry = map[string]routeAccess{
	// access-denials
	"DELETE /api/access-denials":       perm("permission.audit.manage"),
	"GET /api/access-denials":          perm("permission.audit.read"),
	"GET /api/access-denials/archive":  perm("permission.audit.read"),
	"POST /api/access-denials/archive": perm("permission.audit.manage"),

	// admin
	"GET /api/admin/maintenance": role("IsSuperAdmin в обработчике, остальным 403"),
	"PUT /api/admin/maintenance": role("IsSuperAdmin в обработчике перед переключением режима"),

	// announcements
	"POST /api/announcements":            perm("page.admin.directories"),
	"DELETE /api/announcements/:id":      perm("page.admin.directories"),
	"PUT /api/announcements/:id":         perm("page.admin.directories"),
	"POST /api/announcements/:id/hide":   perm("page.admin.directories"),
	"GET /api/announcements/active":      open("активное объявление для всех вошедших"),
	"GET /api/announcements/all":         perm("page.admin.directories"),
	"POST /api/announcements/set-active": perm("page.admin.directories"),

	// application-approvers
	"GET /api/application-approvers":                 perm("page.admin.directories"),
	"POST /api/application-approvers":                perm("page.admin.directories"),
	"DELETE /api/application-approvers/:id":          perm("page.admin.directories"),
	"PATCH /api/application-approvers/:id":           perm("page.admin.directories"),
	"GET /api/application-approvers/available-users": perm("page.admin.directories"),
	"GET /api/application-approvers/history":         perm("page.admin.directories"),
	"GET /api/application-approvers/me":              self("признак «я принимающий» по токену"),
	"GET /api/application-approvers/recipients":      open("имена принимающих для строки получателей заявки"),

	// applications
	"GET /api/applications":                                          scoped("сервис фильтрует по автору, ответственному, читателю; принимающий видит все"),
	"POST /api/applications":                                         self("заявка от себя; чужая организация только с application.organization.override"),
	"GET /api/applications/:id":                                      scoped("CanAccessApplication до отметки прочтения (#2608)"),
	"PUT /api/applications/:id":                                      scoped("CanAccessApplication в обработчике"),
	"POST /api/applications/:id/approve":                             scoped("голос только за себя и только в составе согласующих заявки"),
	"GET /api/applications/:id/archive":                              scoped("как у бланка: CanAccessApplication либо охрана и page.available по вложению"),
	"GET /api/applications/:id/attachments":                          scoped("CanAccessApplication в обработчике"),
	"DELETE /api/applications/:id/blacklist-overrides":               scoped("canManageBlacklistOverride: ответственный по заявке или принимающий"),
	"POST /api/applications/:id/blacklist-overrides":                 scoped("canManageBlacklistOverride: ответственный по заявке или принимающий"),
	"GET /api/applications/:id/blank":                                scoped("canDownloadBlank: CanAccessApplication либо охрана и page.available по вложению"),
	"PUT /api/applications/:id/bureau-note":                          role("заметку бюро ведут только принимающие"),
	"GET /api/applications/:id/check-approval-status":                scoped("CanAccessApplication в обработчике"),
	"PUT /api/applications/:id/dates":                                role("срок меняет только принимающий"),
	"GET /api/applications/:id/details":                              scoped("CanAccessApplication в обработчике"),
	"DELETE /api/applications/:id/elements":                          role("checkAssignmentAllowed: только принимающий"),
	"PUT /api/applications/:id/elements/tables":                      role("checkAssignmentAllowed: только принимающий"),
	"PUT /api/applications/:id/elements/unload-places":               role("checkAssignmentAllowed: только принимающий"),
	"GET /api/applications/:id/files":                                scoped("accessibleApplicationID: CanAccessApplication"),
	"DELETE /api/applications/:id/files/:file_id":                    perm("page.admin"),
	"GET /api/applications/:id/files/:file_id":                       scoped("accessibleApplicationID: CanAccessApplication"),
	"POST /api/applications/:id/forward":                             scoped("CanAccessApplication и круг получателей по роли пересылающего"),
	"GET /api/applications/:id/forward-messages":                     scoped("CanAccessApplication в обработчике"),
	"GET /api/applications/:id/history":                              scoped("CanAccessApplication в обработчике"),
	"GET /api/applications/:id/participants":                         scoped("CanAccessApplication в обработчике"),
	"GET /api/applications/:id/questions":                            scoped("CanAccessApplication в обработчике"),
	"POST /api/applications/:id/questions":                           scoped("CanAccessApplication в обработчике"),
	"POST /api/applications/:id/questions/:questionId/answers":       scoped("CanAccessApplication в обработчике"),
	"POST /api/applications/:id/questions/:questionId/read":          scoped("CanAccessApplication в обработчике"),
	"POST /api/applications/:id/questions/seen":                      scoped("CanAccessApplication в обработчике"),
	"POST /api/applications/:id/read":                                scoped("CanAccessApplication, отметка прочтения своя"),
	"GET /api/applications/:id/reads":                                scoped("CanAccessApplication в обработчике"),
	"GET /api/applications/:id/responsible-users":                    scoped("CanAccessApplication в обработчике"),
	"POST /api/applications/:id/restore-to-work":                     role("только принимающий"),
	"POST /api/applications/:id/revoke-approval":                     scoped("свой голос: строка согласующего по user_id из токена"),
	"POST /api/applications/:id/revoke-from-work":                    role("только принимающий"),
	"GET /api/applications/:id/supplements":                          scoped("CanAccessApplication в обработчике"),
	"POST /api/applications/:id/supplements":                         perm("action.supplement.application"),
	"POST /api/applications/:id/supplements/:sid/approve":            scoped("ensureSupplementVoter: голосует только состав раунда дополнения"),
	"POST /api/applications/:id/supplements/:sid/cancel":             scoped("снять дополнение может только автор заявки"),
	"POST /api/applications/:id/supplements/:sid/revoke-approval":    scoped("ensureSupplementVoter: только состав раунда дополнения"),
	"POST /api/applications/:id/supplements/:sid/take-to-work":       role("решение по дополнению принимает только принимающий"),
	"POST /api/applications/:id/take-to-work":                        role("только принимающий"),
	"GET /api/applications/:id/viewers":                              scoped("CanAccessApplication в обработчике"),
	"POST /api/applications/:id/withdraw":                            scoped("отозвать может только автор заявки"),
	"GET /api/applications/attachable":                               perm("page.admin"),
	"GET /api/applications/available-attachments":                    role("requireSecurityOrAdmin: охрана, админ или page.available"),
	"GET /api/applications/available-attachments/:id":                role("requireSecurityOrAdmin и CanSecurityViewAttachment по вложению"),
	"POST /api/applications/available-attachments/:id/mark-executed": role("requireSecurityOrAdmin и CanSecurityViewAttachment по вложению"),
	"GET /api/applications/export":                                   perm("action.export.applications"),
	"POST /api/applications/files":                                   self("черновик файла на себя, заявки ещё нет"),
	"DELETE /api/applications/files/:id":                             self("удаляет только свой черновик (uploaded_by)"),
	"POST /api/applications/history":                                 scoped("CanAccessApplication по application_id из тела"),
	"POST /api/applications/submit-complete-application":             self("заявка от себя; чужая организация только с application.organization.override"),
	"GET /api/applications/unread-count":                             self("счётчик по своим заявкам"),
	"GET /api/applications/user":                                     self("свои заявки и заявки своей организации"),
	"GET /api/applications/user/status-updates-count":                self("счётчик по своим заявкам и заявкам своей организации"),

	// attachments
	"GET /api/attachments":                             open("справочник шаблонов вложений для формы заявки"),
	"POST /api/attachments":                            perm("page.admin.directories"),
	"DELETE /api/attachments/:id":                      perm("page.admin.directories"),
	"GET /api/attachments/:id":                         open("карточка шаблона вложения, общий справочник"),
	"PUT /api/attachments/:id":                         perm("page.admin.directories"),
	"POST /api/attachments/:id/attach-to-application":  perm("page.admin"),
	"GET /api/attachments/:id/blank-template":          perm("action.import.list"),
	"GET /api/attachments/:id/cars":                    scoped("CanAccessApplication и CanViewAttachment в обработчике, id - вложение заявки"),
	"GET /api/attachments/:id/custom-fields":           perm("page.admin.directories"),
	"POST /api/attachments/:id/custom-fields":          perm("page.admin.directories"),
	"GET /api/attachments/:id/employees":               scoped("CanAccessApplication и CanViewAttachment в обработчике, id - вложение заявки"),
	"GET /api/attachments/:id/field-config":            open("настройка полей шаблона для формы заявки"),
	"PUT /api/attachments/:id/field-config":            perm("page.admin.directories"),
	"GET /api/attachments/:id/history":                 perm("page.admin.directories"),
	"POST /api/attachments/:id/import-list":            perm("action.import.list"),
	"GET /api/attachments/:id/items":                   scoped("CanAccessApplication и CanViewAttachment в обработчике, id - вложение заявки"),
	"PUT /api/attachments/:id/restore":                 perm("page.admin.directories"),
	"DELETE /api/attachments/:id/template":             perm("page.admin.directories"),
	"GET /api/attachments/:id/template":                perm("page.admin.directories"),
	"POST /api/attachments/:id/template":               perm("page.admin.directories"),
	"GET /api/attachments/:id/template-fields":         perm("page.admin.directories"),
	"DELETE /api/attachments/:id/template/:tid":        perm("page.admin.directories"),
	"PUT /api/attachments/:id/template/:tid/activate":  perm("page.admin.directories"),
	"GET /api/attachments/:id/template/:tid/file":      perm("page.admin.directories"),
	"POST /api/attachments/:id/template/copy-mappings": perm("page.admin.directories"),
	"PUT /api/attachments/:id/template/deactivate":     perm("page.admin.directories"),
	"GET /api/attachments/:id/template/file":           perm("page.admin.directories"),
	"PUT /api/attachments/:id/template/mappings":       perm("page.admin.directories"),
	"PUT /api/attachments/:id/template/params":         perm("page.admin.directories"),
	"GET /api/attachments/:id/templates":               perm("page.admin.directories"),
	"GET /api/attachments/all":                         perm("page.admin.directories"),
	"DELETE /api/attachments/custom-fields/:fid":       perm("page.admin.directories"),
	"PUT /api/attachments/custom-fields/:fid":          perm("page.admin.directories"),
	"GET /api/attachments/template-sources":            perm("page.admin.directories"),

	// audit
	"GET /api/audit": perm("page.admin"),

	// bug-report
	"POST /api/bug-report": self("отчёт об ошибке от себя"),

	// bureau
	"GET /api/bureau/time-slots":             open("расписание бюро для окна режимов работы"),
	"POST /api/bureau/time-slots":            perm("page.admin"),
	"DELETE /api/bureau/time-slots/:slot_id": perm("page.admin"),
	"PUT /api/bureau/time-slots/:slot_id":    perm("page.admin"),

	// cars
	"PUT /api/cars/:id/activate":                     perm("page.admin"),
	"PUT /api/cars/:id/deactivate":                   perm("page.admin"),
	"GET /api/cars/:id/history":                      scoped("requireElementVisible по ElementScope: свой пост, заявка, организация или компания (#2610)"),
	"POST /api/cars/:id/history":                     perm("page.admin"),
	"PUT /api/cars/:id/restore":                      perm("page.admin"),
	"PUT /api/cars/:id/territory-status":             perm("table.{post}.entry"),
	"PUT /api/cars/:id/territory-status/revert":      perm("table.{post}.entry"),
	"GET /api/cars/active-for-table/:id":             perm("table.{post}.view"),
	"POST /api/cars/bulk/add-table":                  perm("page.admin"),
	"POST /api/cars/bulk/move-table":                 perm("page.admin"),
	"POST /api/cars/bulk/unbind-table":               perm("page.admin"),
	"GET /api/cars/check-active":                     scoped("своя организация; чужая только админу или с application.organization.override (#1437)"),
	"GET /api/cars/fact-for-table/:id":               perm("table.{post}.view"),
	"GET /api/cars/fact-unload-places":               scoped("ElementScopeResolver фильтрует по своим постам, заявкам, организации (#2610)"),
	"GET /api/cars/history/all":                      perm("page.admin"),
	"GET /api/cars/history/current-status":           scoped("ElementScopeResolver фильтрует по своим постам, заявкам, организации (#2610)"),
	"GET /api/cars/history/filter-options":           perm("page.admin"),
	"GET /api/cars/history/table/:id":                perm("table.{post}.history"),
	"GET /api/cars/history/table/:id/filter-options": perm("table.{post}.history"),
	"GET /api/cars/history/unified":                  scoped("ElementScopeResolver, page.admin.blacklist видит всё (#2610)"),
	"POST /api/cars/manual":                          perm("entity.cars.manual_add"),
	"GET /api/cars/unload-places":                    scoped("ElementScopeResolver фильтрует по своим постам, заявкам, организации (#2610)"),

	// citizenships
	"GET /api/citizenships":                open("справочник гражданств для формы заявки"),
	"POST /api/citizenships":               perm("page.admin.directories"),
	"DELETE /api/citizenships/:id":         perm("page.admin.directories"),
	"PUT /api/citizenships/:id":            perm("page.admin.directories"),
	"GET /api/citizenships/:id/history":    open("история справочника гражданств открыта вошедшим (router.go, комментарий у группы)"),
	"POST /api/citizenships/:id/restore":   perm("page.admin.directories"),
	"POST /api/citizenships/bulk/archive":  perm("page.admin.directories"),
	"POST /api/citizenships/bulk/restore":  perm("page.admin.directories"),
	"POST /api/citizenships/clear-default": perm("page.admin.directories"),

	// companies
	"GET /api/companies":                         open("справочник компаний для формы заявки"),
	"POST /api/companies":                        perm("page.admin.directories"),
	"DELETE /api/companies/:id":                  perm("page.admin.directories"),
	"PUT /api/companies/:id":                     perm("page.admin.directories"),
	"GET /api/companies/:id/history":             perm("page.admin.directories"),
	"GET /api/companies/:id/members":             perm("page.admin.directories"),
	"POST /api/companies/:id/moderation/approve": perm("application.organization.moderate"),
	"POST /api/companies/:id/moderation/merge":   perm("application.organization.moderate"),
	"PATCH /api/companies/:id/moderation/rename": perm("application.organization.moderate"),
	"POST /api/companies/:id/reassign-users":     perm("page.admin.directories"),
	"POST /api/companies/:id/restore":            perm("page.admin.directories"),
	"GET /api/companies/:id/tables":              open("посты любой компании: подача заявки за чужую организацию"),
	"PUT /api/companies/:id/tables":              perm("page.admin.directories"),
	"GET /api/companies/:id/unload-places":       open("места разгрузки любой компании: подача за чужую организацию"),
	"PUT /api/companies/:id/unload-places":       perm("page.admin.directories"),
	"GET /api/companies/:id/users":               open("ответственные любой компании для выбора получателя, required_approval маскируется"),
	"PUT /api/companies/:id/users":               perm("page.admin.directories"),
	"POST /api/companies/bulk/archive":           perm("page.admin.directories"),
	"POST /api/companies/bulk/restore":           perm("page.admin.directories"),
	"POST /api/companies/bulk/tables":            perm("page.admin.directories"),
	"POST /api/companies/bulk/type":              perm("page.admin.directories"),
	"POST /api/companies/bulk/unload-places":     perm("page.admin.directories"),
	"POST /api/companies/bulk/users":             perm("page.admin.directories"),
	"GET /api/companies/suggest":                 perm("application.organization.override"),
	"GET /api/companies/with-users":              perm("page.admin.directories"),
	"GET /api/companies/with-users-extended":     perm("page.admin.directories"),

	// consents
	"GET /api/consents":             self("свои согласия по токену"),
	"POST /api/consents":            self("согласие за себя по токену"),
	"DELETE /api/consents/:type":    self("отзыв своего согласия"),
	"POST /api/consents/accept":     self("подтверждение своего согласия"),
	"GET /api/consents/check/:type": self("проверка своего согласия"),
	"GET /api/consents/gate":        self("состояние гейта согласия для себя"),

	// document-groups
	"GET /api/document-groups":         perm("page.admin.directories"),
	"POST /api/document-groups":        perm("page.admin.directories"),
	"DELETE /api/document-groups/:id":  perm("page.admin.directories"),
	"PUT /api/document-groups/:id":     perm("page.admin.directories"),
	"PUT /api/document-groups/reorder": perm("page.admin.directories"),

	// documents
	"GET /api/documents":              perm("page.admin.directories"),
	"POST /api/documents":             perm("page.admin.directories"),
	"DELETE /api/documents/:id":       perm("page.admin.directories"),
	"PUT /api/documents/:id":          perm("page.admin.directories"),
	"GET /api/documents/:id/download": scoped("видимый документ всем, скрытый только с page.admin.directories (#2621)"),
	"PUT /api/documents/:id/file":     perm("page.admin.directories"),
	"PUT /api/documents/reorder":      perm("page.admin.directories"),

	// employees
	"PUT /api/employees/:id/activate":                     perm("page.admin"),
	"PUT /api/employees/:id/deactivate":                   perm("page.admin"),
	"GET /api/employees/:id/history":                      scoped("requireElementVisible по ElementScope: свой пост, заявка, организация или компания (#2610)"),
	"PUT /api/employees/:id/restore":                      perm("page.admin"),
	"PUT /api/employees/:id/territory-status":             perm("table.{post}.entry"),
	"PUT /api/employees/:id/territory-status/revert":      perm("table.{post}.entry"),
	"GET /api/employees/active-for-table/:id":             perm("table.{post}.view"),
	"POST /api/employees/bulk/add-table":                  perm("page.admin"),
	"POST /api/employees/bulk/move-table":                 perm("page.admin"),
	"POST /api/employees/bulk/unbind-table":               perm("page.admin"),
	"GET /api/employees/history/all":                      perm("page.admin"),
	"GET /api/employees/history/current-status":           scoped("ElementScopeResolver фильтрует по своим постам, заявкам, организации (#2610)"),
	"GET /api/employees/history/filter-options":           perm("page.admin"),
	"GET /api/employees/history/table/:id":                perm("table.{post}.history"),
	"GET /api/employees/history/table/:id/filter-options": perm("table.{post}.history"),
	"GET /api/employees/history/unified":                  scoped("ElementScopeResolver, page.admin.blacklist видит всё (#2610)"),
	"POST /api/employees/manual":                          perm("entity.employees.manual_add"),

	// events
	"GET /api/events":         public("вне JWT: EventSource не шлёт заголовок, вход по одноразовому билету из POST /events/ticket"),
	"POST /api/events/ticket": self("билет потока событий на себя по токену"),

	// feedback
	"POST /api/feedback":           self("обращение от себя"),
	"PUT /api/feedback/:id/flag":   perm("page.admin.feedback"),
	"PUT /api/feedback/:id/read":   perm("page.admin.feedback"),
	"PUT /api/feedback/:id/status": perm("page.admin.feedback"),
	"GET /api/feedback/all":        perm("page.admin.feedback"),
	"GET /api/feedback/my":         self("свои обращения"),
	"GET /api/feedback/stats":      perm("page.admin.feedback"),

	// file-archive
	"POST /api/file-archive/applications/:id/reexport": perm("page.admin.file_archive", "action.manage.file_archive"),
	"POST /api/file-archive/backfill":                  perm("page.admin.file_archive", "action.manage.file_archive"),
	"GET /api/file-archive/download":                   public("вне JWT: ссылку открывает браузер, доступ по одноразовому билету с пользователем, правом и периодом"),
	"POST /api/file-archive/download-ticket":           perm("page.admin.file_archive", "action.download.file_archive"),
	"POST /api/file-archive/estimate":                  perm("page.admin.file_archive"),
	"GET /api/file-archive/files/:id":                  perm("page.admin.file_archive", "action.download.file_archive"),
	"GET /api/file-archive/items":                      perm("page.admin.file_archive"),
	"GET /api/file-archive/settings":                   perm("page.admin.file_archive"),
	"GET /api/file-archive/stats":                      perm("page.admin.file_archive"),

	// get-organization
	"GET /api/get-organization": self("своя организация по токену"),

	// guide
	"GET /api/guide/admin/sections":               perm("page.admin"),
	"PUT /api/guide/admin/sections/:role":         perm("page.admin"),
	"DELETE /api/guide/admin/sections/:role/file": perm("page.admin"),
	"PUT /api/guide/admin/sections/:role/file":    perm("page.admin"),
	"GET /api/guide/sections":                     scoped("ListForUser отдаёт только разделы с правом guide.<роль>"),
	"GET /api/guide/sections/:role/download":      scoped("GetSectionForUser проверяет guide.<роль>, без права 403"),

	// impersonation
	"POST /api/impersonation/stop": self("выход из своей сессии имперсонации, актор из токена"),

	// license-plate-formats
	"GET /api/license-plate-formats":               open("справочник форматов номеров для формы заявки"),
	"POST /api/license-plate-formats":              perm("page.admin.directories"),
	"DELETE /api/license-plate-formats/:id":        perm("page.admin.directories"),
	"PUT /api/license-plate-formats/:id":           perm("page.admin.directories"),
	"GET /api/license-plate-formats/:id/history":   open("история правок справочника форматов, без ПД"),
	"POST /api/license-plate-formats/:id/restore":  perm("page.admin.directories"),
	"POST /api/license-plate-formats/bulk/archive": perm("page.admin.directories"),
	"POST /api/license-plate-formats/bulk/restore": perm("page.admin.directories"),

	// login
	"POST /api/login": public("вход"),

	// logout
	"POST /api/logout": self("отзыв своей сессии"),

	// logout-all
	"POST /api/logout-all": self("отзыв всех своих сессий"),

	// marks
	"GET /api/marks":               open("справочник марок для формы заявки"),
	"POST /api/marks":              perm("page.admin.directories"),
	"PUT /api/marks/:id":           perm("page.admin.directories"),
	"POST /api/marks/:id/archive":  perm("page.admin.directories"),
	"GET /api/marks/:id/history":   open("история справочника марок, без ПД"),
	"POST /api/marks/:id/restore":  perm("page.admin.directories"),
	"POST /api/marks/bulk/archive": perm("page.admin.directories"),
	"POST /api/marks/bulk/restore": perm("page.admin.directories"),

	// news
	"GET /api/news":        open("лента активных новостей для всех вошедших"),
	"POST /api/news":       perm("page.admin.directories"),
	"DELETE /api/news/:id": perm("page.admin.directories"),
	"PUT /api/news/:id":    perm("page.admin.directories"),
	"GET /api/news/all":    perm("page.admin.directories"),

	// notifications
	"DELETE /api/notifications":                self("свои уведомления по user_id из токена"),
	"GET /api/notifications":                   self("свои уведомления по user_id из токена"),
	"POST /api/notifications":                  perm("page.admin"),
	"DELETE /api/notifications/:id":            self("findOwned в сервисе: чужой id - не найдено"),
	"PUT /api/notifications/:id/read":          self("findOwned в сервисе: чужой id - не найдено"),
	"GET /api/notifications/preferences":       self("свои подписки"),
	"PUT /api/notifications/preferences":       self("свои подписки"),
	"GET /api/notifications/push/status":       self("свои устройства push"),
	"DELETE /api/notifications/push/subscribe": self("своя подписка push"),
	"POST /api/notifications/push/subscribe":   self("своя подписка push"),
	"GET /api/notifications/push/summary":      perm("page.statistics"),
	"PUT /api/notifications/read-all":          self("свои уведомления по user_id из токена"),

	// onboarding
	"GET /api/onboarding":           self("статус тура по user_id из токена"),
	"POST /api/onboarding/complete": self("отметка тура по user_id из токена"),

	// organizations
	"GET /api/organizations":                         open("наименования активных организаций для формы заявки"),
	"POST /api/organizations":                        perm("page.admin.directories"),
	"DELETE /api/organizations/:id":                  perm("page.admin.directories"),
	"PUT /api/organizations/:id":                     perm("page.admin.directories"),
	"GET /api/organizations/:id/history":             perm("page.admin.directories"),
	"GET /api/organizations/:id/members":             perm("page.admin.directories"),
	"POST /api/organizations/:id/moderation/approve": perm("application.organization.moderate"),
	"POST /api/organizations/:id/moderation/merge":   perm("application.organization.moderate"),
	"PATCH /api/organizations/:id/moderation/rename": perm("application.organization.moderate"),
	"POST /api/organizations/:id/reassign-users":     perm("page.admin.directories"),
	"POST /api/organizations/:id/restore":            perm("page.admin.directories"),
	"GET /api/organizations/:id/tables":              open("посты любой организации: подача заявки за чужую организацию"),
	"PUT /api/organizations/:id/tables":              perm("page.admin.directories"),
	"GET /api/organizations/:id/unload-places":       open("места разгрузки любой организации: подача за чужую организацию"),
	"PUT /api/organizations/:id/unload-places":       perm("page.admin.directories"),
	"GET /api/organizations/:id/users":               open("ответственные любой организации для выбора получателя (#2013), required_approval маскируется"),
	"PUT /api/organizations/:id/users":               perm("page.admin.directories"),
	"POST /api/organizations/bulk/archive":           perm("page.admin.directories"),
	"POST /api/organizations/bulk/restore":           perm("page.admin.directories"),
	"POST /api/organizations/bulk/tables":            perm("page.admin.directories"),
	"POST /api/organizations/bulk/type":              perm("page.admin.directories"),
	"POST /api/organizations/bulk/unload-places":     perm("page.admin.directories"),
	"POST /api/organizations/bulk/users":             perm("page.admin.directories"),
	"GET /api/organizations/suggest":                 perm("application.organization.override"),
	"GET /api/organizations/with-users":              perm("page.admin.directories"),
	"GET /api/organizations/with-users-extended":     perm("page.admin.directories"),

	// pd-audit
	"GET /api/pd-audit": perm("page.admin.pd_audit"),

	// pd-subject
	"GET /api/pd-subject/candidates":  perm("page.admin.pd_subject"),
	"GET /api/pd-subject/disclosures": perm("page.admin.pd_subject"),
	"POST /api/pd-subject/export":     perm("page.admin.pd_subject", "action.pd_subject.export"),
	"GET /api/pd-subject/report":      perm("page.admin.pd_subject"),

	// permission-groups
	"GET /api/permission-groups":        perm("permission.audit.manage"),
	"POST /api/permission-groups":       perm("permission.audit.manage"),
	"DELETE /api/permission-groups/:id": perm("permission.audit.manage"),
	"GET /api/permission-groups/:id":    perm("permission.audit.manage"),
	"PUT /api/permission-groups/:id":    perm("permission.audit.manage"),
	"POST /api/permission-groups/merge": perm("permission.audit.manage"),

	// permissions
	"POST /api/permissions/auto-generate":     perm("page.admin.tables_constructor"),
	"GET /api/permissions/catalog":            perm("permission.audit.manage"),
	"GET /api/permissions/my":                 self("свои права по токену"),
	"GET /api/permissions/user/:id":           perm("permission.audit.manage"),
	"PUT /api/permissions/user/:id":           perm("permission.audit.manage"),
	"GET /api/permissions/user/:id/effective": perm("permission.audit.manage"),

	// person-blacklist
	"GET /api/person-blacklist":               perm("page.admin.blacklist"),
	"POST /api/person-blacklist":              perm("page.admin.blacklist"),
	"DELETE /api/person-blacklist/:id":        perm("page.admin.blacklist"),
	"PUT /api/person-blacklist/:id":           perm("page.admin.blacklist"),
	"GET /api/person-blacklist/:id/history":   perm("page.admin.blacklist"),
	"DELETE /api/person-blacklist/:id/purge":  perm("page.admin.blacklist"),
	"POST /api/person-blacklist/:id/restore":  perm("page.admin.blacklist"),
	"POST /api/person-blacklist/bulk/archive": perm("page.admin.blacklist"),
	"POST /api/person-blacklist/bulk/restore": perm("page.admin.blacklist"),
	"GET /api/person-blacklist/check":         open("точечная проверка человека для формы заявки, полный список за page.admin.blacklist"),
	"GET /api/person-blacklist/history":       perm("page.admin.blacklist"),
	"GET /api/person-blacklist/impact":        perm("page.admin.blacklist"),

	// public
	"GET /api/public/documents": open("витрина документов с is_visible, скрытые не отдаются"),

	// refresh-token
	"POST /api/refresh-token": public("вне JWT: обмен refresh-cookie на новую пару токенов"),

	// request-logs
	"GET /api/request-logs":          perm("page.admin.monitoring"),
	"GET /api/request-logs/export":   perm("page.admin.monitoring"),
	"GET /api/request-logs/history":  perm("page.admin.monitoring"),
	"GET /api/request-logs/realtime": perm("page.admin.monitoring"),
	"GET /api/request-logs/stats":    perm("page.admin.monitoring"),
	"GET /api/request-logs/timeline": perm("page.admin.monitoring"),
	"GET /api/request-logs/users":    perm("page.admin.monitoring"),

	// roles
	"GET /api/roles":                    perm("permission.audit.manage"),
	"POST /api/roles":                   perm("permission.audit.manage"),
	"DELETE /api/roles/:id":             perm("permission.audit.manage"),
	"PUT /api/roles/:id":                perm("permission.audit.manage"),
	"PUT /api/roles/:id/default-groups": perm("permission.audit.manage"),
	"PUT /api/roles/:id/permissions":    perm("permission.audit.manage"),

	// search
	"GET /api/search": open("разделы поиска отсекаются по праву при выборе провайдеров, строки внутри провайдера"),

	// settings
	"GET /api/settings":                               perm("page.admin.settings"),
	"PUT /api/settings/:key":                          perm("page.admin.settings"),
	"GET /api/settings/contacts":                      public("контакты бюро на экране входа"),
	"DELETE /api/settings/data-processing/document":   perm("page.admin"),
	"GET /api/settings/data-processing/document":      open("документ о согласии на обработку ПД, его показывают каждому до согласия"),
	"POST /api/settings/data-processing/document":     perm("page.admin"),
	"GET /api/settings/data-processing/document/meta": open("метаданные того же документа"),
	"GET /api/settings/mail/status":                   perm("page.admin.settings"),
	"POST /api/settings/mail/test":                    perm("page.admin.settings"),
	"GET /api/settings/maintenance":                   public("статус техработ для экрана входа и страницы техработ"),
	"GET /api/settings/notifications":                 open("общие тайминги уведомлений, не персональные"),
	"GET /api/settings/password-policy":               open("требования к паролю для формы смены пароля"),
	"GET /api/settings/password-rotation/last":        perm("page.admin.settings"),
	"POST /api/settings/password-rotation/run":        perm("action.password.rotate_all"),
	"GET /api/settings/password-rotation/status":      perm("page.admin.settings"),
	"GET /api/settings/pd-consent":                    perm("page.admin"),
	"GET /api/settings/pd-consent/collection":         perm("page.admin"),
	"POST /api/settings/pd-consent/require-again":     perm("page.admin"),
	"PUT /api/settings/pd-consent/required":           perm("page.admin"),
	"PUT /api/settings/pd-consent/text":               perm("page.admin"),
	"GET /api/settings/upload":                        open("лимит размера файла для форм загрузки"),

	// system-tables
	"GET /api/system-tables":                                         open("список постов для выбора места в форме заявки"),
	"POST /api/system-tables":                                        perm("page.admin.tables_constructor"),
	"DELETE /api/system-tables/:id":                                  perm("page.admin.tables_constructor"),
	"GET /api/system-tables/:id":                                     open("конфигурация поста без состава, состав за table.<пост>.view"),
	"PUT /api/system-tables/:id":                                     perm("page.admin.tables_constructor"),
	"DELETE /api/system-tables/:id/companies/:company_id":            perm("page.admin"),
	"POST /api/system-tables/:id/detach-all":                         perm("page.admin"),
	"PUT /api/system-tables/:id/fact-fields":                         perm("page.admin.tables_constructor"),
	"PUT /api/system-tables/:id/fields":                              perm("page.admin.tables_constructor"),
	"GET /api/system-tables/:id/history":                             open("журнал изменений конфигурации поста"),
	"DELETE /api/system-tables/:id/organizations/:org_id":            perm("page.admin"),
	"GET /api/system-tables/:id/pass-report/live":                    perm("table.{post}.report"),
	"GET /api/system-tables/:id/pass-reports":                        perm("table.{post}.report"),
	"POST /api/system-tables/:id/photos":                             perm("page.admin.tables_constructor"),
	"POST /api/system-tables/:id/restore":                            perm("page.admin.tables_constructor"),
	"DELETE /api/system-tables/:id/snapshots":                        perm("page.admin"),
	"GET /api/system-tables/:id/snapshots":                           perm("table.{post}.versions"),
	"POST /api/system-tables/:id/snapshots":                          perm("table.{post}.versions"),
	"GET /api/system-tables/:id/snapshots/:sid":                      perm("table.{post}.versions"),
	"GET /api/system-tables/:id/snapshots/:sid/export":               perm("table.{post}.versions"),
	"GET /api/system-tables/:id/time-slots":                          open("окна времени поста для формы заявки"),
	"POST /api/system-tables/:id/time-slots":                         perm("page.admin.tables_constructor"),
	"DELETE /api/system-tables/:id/trash":                            perm("table.{post}.trash"),
	"GET /api/system-tables/:id/trash":                               perm("table.{post}.trash"),
	"DELETE /api/system-tables/:id/trash/:item_id":                   perm("table.{post}.trash"),
	"GET /api/system-tables/:id/trash/history":                       perm("table.{post}.trash"),
	"POST /api/system-tables/:id/trash/restore":                      perm("table.{post}.trash"),
	"GET /api/system-tables/:id/usage":                               open("счётчики организаций и компаний, привязанных к посту"),
	"GET /api/system-tables/:id/warning-windows":                     open("предупреждающие окна поста для формы заявки"),
	"POST /api/system-tables/:id/warning-windows":                    perm("page.admin.tables_constructor"),
	"DELETE /api/system-tables/:table_id/photos/:photo_id":           perm("page.admin.tables_constructor"),
	"POST /api/system-tables/:table_id/photos/:photo_id/main":        perm("page.admin.tables_constructor"),
	"DELETE /api/system-tables/:table_id/time-slots/:slot_id":        perm("page.admin.tables_constructor"),
	"PUT /api/system-tables/:table_id/time-slots/:slot_id":           perm("page.admin.tables_constructor"),
	"DELETE /api/system-tables/:table_id/warning-windows/:window_id": perm("page.admin.tables_constructor"),
	"PUT /api/system-tables/:table_id/warning-windows/:window_id":    perm("page.admin.tables_constructor"),
	"POST /api/system-tables/bulk/archive":                           perm("page.admin.tables_constructor"),
	"POST /api/system-tables/bulk/restore":                           perm("page.admin.tables_constructor"),
	"GET /api/system-tables/name/:name":                              open("конфигурация поста по имени, как GET /system-tables/:id"),

	// unique-cars
	"GET /api/unique-cars":                scoped("по умолчанию свои записи, организация и компания только свои, вся система только админу"),
	"POST /api/unique-cars":               scoped("checkRegistryBinding: чужая организация только с override (#2630)"),
	"DELETE /api/unique-cars/:id":         scoped("canEditCar: свой, своя организация или компания, админ"),
	"PUT /api/unique-cars/:id":            scoped("canEditCar и checkRegistryBinding при смене привязки (#2630)"),
	"GET /api/unique-cars/:id/history":    scoped("canEditCar перед выдачей журнала машины"),
	"GET /api/unique-cars/history":        role("журнал реестра целиком только админу (CanManageAll)"),
	"GET /api/unique-cars/lookup":         perm("page.admin.blacklist"),
	"GET /api/unique-cars/ownership-info": self("своя привязка к организации и компании"),

	// unique-employees
	"GET /api/unique-employees":                  scoped("по умолчанию свои записи, организация и компания только свои, вся система только админу"),
	"POST /api/unique-employees":                 scoped("checkRegistryBinding: чужая организация только с override (#2630)"),
	"DELETE /api/unique-employees/:id":           scoped("canEditEmployee: свой, своя организация или компания, админ"),
	"PUT /api/unique-employees/:id":              scoped("canEditEmployee и checkRegistryBinding при смене привязки (#2630)"),
	"GET /api/unique-employees/:id/history":      scoped("canEditEmployee перед выдачей журнала сотрудника"),
	"DELETE /api/unique-employees/:id/objection": role("снять возражение может только админ (CanManageAll)"),
	"POST /api/unique-employees/:id/objection":   scoped("canEditEmployee: тот же круг, что правит запись"),
	"GET /api/unique-employees/history":          role("журнал реестра целиком только админу (CanManageAll)"),
	"GET /api/unique-employees/lookup":           perm("page.admin.blacklist"),
	"GET /api/unique-employees/ownership-info":   self("своя привязка к организации и компании"),

	// unload-places
	"GET /api/unload-places":                                         open("справочник мест разгрузки для формы заявки"),
	"POST /api/unload-places":                                        perm("page.admin.directories"),
	"DELETE /api/unload-places/:id":                                  perm("page.admin.directories"),
	"GET /api/unload-places/:id":                                     open("карточка места разгрузки для формы заявки"),
	"PUT /api/unload-places/:id":                                     perm("page.admin.directories"),
	"DELETE /api/unload-places/:id/companies/:company_id":            perm("page.admin.directories"),
	"POST /api/unload-places/:id/detach-all":                         perm("page.admin.directories"),
	"GET /api/unload-places/:id/history":                             open("история справочника мест разгрузки, без ПД"),
	"DELETE /api/unload-places/:id/organizations/:org_id":            perm("page.admin.directories"),
	"POST /api/unload-places/:id/photos":                             perm("page.admin.directories"),
	"POST /api/unload-places/:id/restore":                            perm("page.admin.directories"),
	"GET /api/unload-places/:id/time-slots":                          open("окна времени места разгрузки для формы заявки"),
	"POST /api/unload-places/:id/time-slots":                         perm("page.admin.directories"),
	"GET /api/unload-places/:id/usage":                               open("привязки места к организациям и компаниям"),
	"GET /api/unload-places/:id/warning-windows":                     open("предупреждающие окна места для формы заявки"),
	"POST /api/unload-places/:id/warning-windows":                    perm("page.admin.directories"),
	"DELETE /api/unload-places/:place_id/photos/:photo_id":           perm("page.admin.directories"),
	"POST /api/unload-places/:place_id/photos/:photo_id/main":        perm("page.admin.directories"),
	"DELETE /api/unload-places/:place_id/time-slots/:slot_id":        perm("page.admin.directories"),
	"PUT /api/unload-places/:place_id/time-slots/:slot_id":           perm("page.admin.directories"),
	"DELETE /api/unload-places/:place_id/warning-windows/:window_id": perm("page.admin.directories"),
	"PUT /api/unload-places/:place_id/warning-windows/:window_id":    perm("page.admin.directories"),
	"POST /api/unload-places/bulk/archive":                           perm("page.admin.directories"),
	"POST /api/unload-places/bulk/restore":                           perm("page.admin.directories"),

	// uploads
	"GET /api/uploads*": scoped("mw.FileAccess: закрытый список каталогов (#2498), сканы заявки по доступу к ней (#2465)"),

	// user-data
	"GET /api/user-data": self("свои данные по токену"),

	// user-types
	"GET /api/user-types": public("типы учёток до входа"),

	// user-types-management
	"GET /api/user-types-management":                     perm("page.admin.directories"),
	"POST /api/user-types-management":                    perm("page.admin.directories"),
	"DELETE /api/user-types-management/:id":              perm("page.admin.directories"),
	"PUT /api/user-types-management/:id":                 perm("page.admin.directories"),
	"GET /api/user-types-management/:id/blocking-users":  perm("page.admin.directories"),
	"GET /api/user-types-management/:id/history":         perm("page.admin.directories"),
	"POST /api/user-types-management/:id/reassign-users": perm("page.admin.directories"),

	// users
	"POST /api/users":                                        perm("page.admin.users"),
	"PUT /api/users/:id/admin":                               perm("action.grant.admin"),
	"POST /api/users/:id/ban":                                perm("action.ban.user"),
	"POST /api/users/:id/impersonate":                        perm("user.impersonate"),
	"PUT /api/users/:id/role":                                perm("permission.audit.manage"),
	"POST /api/users/:id/unban":                              perm("action.ban.user"),
	"GET /api/users/:user_id/permission-groups":              perm("permission.audit.manage"),
	"DELETE /api/users/:user_id/permission-groups/:group_id": perm("permission.audit.manage"),
	"POST /api/users/:user_id/permission-groups/:group_id":   perm("permission.audit.manage"),
	"DELETE /api/users/:username":                            perm("page.admin.users"),
	"GET /api/users/:username/auth-events":                   perm("page.admin.users"),
	"PUT /api/users/:username/company":                       perm("page.admin.users"),
	"DELETE /api/users/:username/consent":                    perm("page.admin.users"),
	"GET /api/users/:username/history":                       perm("page.admin.users"),
	"PUT /api/users/:username/info":                          perm("page.admin.users"),
	"POST /api/users/:username/onboarding/reset":             perm("page.admin"),
	"PUT /api/users/:username/organization":                  perm("page.admin.users"),
	"PUT /api/users/:username/password":                      perm("page.admin.users"),
	"POST /api/users/:username/reset-lockout":                perm("page.admin.users"),
	"POST /api/users/:username/restore":                      perm("page.admin.users"),
	"POST /api/users/:username/rotate-password":              perm("page.admin.users"),
	"GET /api/users/:username/tables":                        perm("page.admin.users"),
	"PUT /api/users/:username/tables":                        perm("page.admin.users"),
	"PUT /api/users/:username/type":                          perm("page.admin.users"),
	"GET /api/users/:username/unload-places":                 perm("page.admin.users"),
	"PUT /api/users/:username/unload-places":                 perm("page.admin.users"),
	"GET /api/users/all":                                     perm("page.admin.users"),
	"POST /api/users/bulk/archive":                           perm("page.admin.users"),
	"POST /api/users/bulk/ban":                               perm("action.ban.user"),
	"POST /api/users/bulk/company":                           perm("page.admin.users"),
	"POST /api/users/bulk/organization":                      perm("page.admin.users"),
	"POST /api/users/bulk/restore":                           perm("page.admin.users"),
	"POST /api/users/bulk/type":                              perm("page.admin.users"),
	"POST /api/users/bulk/unban":                             perm("action.ban.user"),
	"GET /api/users/current":                                 self("своя учётка по токену, алиас /me"),
	"GET /api/users/me":                                      self("своя учётка по токену"),
	"PUT /api/users/me/password":                             self("свой пароль по токену с проверкой текущего"),
	"GET /api/users/me/theme":                                self("своя тема оформления"),
	"PUT /api/users/me/theme":                                self("своя тема оформления"),
	"GET /api/users/recipient-candidates":                    scoped("коллеги своей организации и компании плюс руководители, ПД маскируются (#1567)"),

	// vehicle-blacklist
	"GET /api/vehicle-blacklist":               perm("page.admin.blacklist"),
	"POST /api/vehicle-blacklist":              perm("page.admin.blacklist"),
	"DELETE /api/vehicle-blacklist/:id":        perm("page.admin.blacklist"),
	"PUT /api/vehicle-blacklist/:id":           perm("page.admin.blacklist"),
	"GET /api/vehicle-blacklist/:id/history":   perm("page.admin.blacklist"),
	"DELETE /api/vehicle-blacklist/:id/purge":  perm("page.admin.blacklist"),
	"POST /api/vehicle-blacklist/:id/restore":  perm("page.admin.blacklist"),
	"POST /api/vehicle-blacklist/bulk/archive": perm("page.admin.blacklist"),
	"POST /api/vehicle-blacklist/bulk/restore": perm("page.admin.blacklist"),
	"GET /api/vehicle-blacklist/check":         open("точечная проверка номера для формы заявки, полный список за page.admin.blacklist"),
	"GET /api/vehicle-blacklist/history":       perm("page.admin.blacklist"),
	"GET /api/vehicle-blacklist/impact":        perm("page.admin.blacklist"),

	// work-modes
	"GET /api/work-modes": open("сводка режимов работы бюро, мест разгрузки и постов, без ПД"),

	// /health
	"GET /health": public("проверка живости для мониторинга"),
}
