name: TgBridge
version: 1.0.1
main: dev.keeq0.tgbridge.TgBridge
api-version: '1.21'
description: Мост между игровым чатом и топиком Telegram
author: keeq0
commands:
  tgbridge:
    description: Управление мостом
    usage: /tgbridge <reload|status>
    aliases: [tgb]
permissions:
  tgbridge.admin:
    description: Управление мостом
    default: op
